apiVersion: apps/v1
kind: Deployment
metadata: 
  name: agent10004
  labels: 
    app: agent10004
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent10004
  template:
    metadata:
      labels:
        app: agent10004
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: agent10004
        image: zeinabne/edge-testbed:vehagent1
        imagePullPolicy: Always
        ports:
        - containerPort: 32004
        args: ["10004", "2000", "80", "200", "80", "1"]
      nodeSelector:
        nn: master
---
apiVersion: v1
kind: Service
metadata:
  name: agent10004-service
spec:
  selector:
    app: agent10004
  type: NodePort
  ports:
    - protocol: TCP
      port: 32004
      name: listener
      targetPort: 32004
      nodePort: 32004