apiVersion: apps/v1
kind: Deployment
metadata: 
  name: agent10008
  labels: 
    app: agent10008
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent10008
  template:
    metadata:
      labels:
        app: agent10008
    spec:
      imagePullSecrets:
      - name: 
      containers:
      - name: agent10008
        image: zeinabne/smotec:vehicleagent
        imagePullPolicy: Always
        ports:
        - containerPort: 32008
        args: ["10008", "100", "200", "80", "1"]
        volumeMounts:
        - name: testbedconfig
          mountPath: /tmp/src/conf/TestbedConfig.json
          subPath: TestbedConfig.json
      volumes:
      - name: testbedconfig
        configMap:
          name: testbedconfig
      nodeSelector:
        nn: master
---
apiVersion: v1
kind: Service
metadata:
  name: agent10008-service
spec:
  selector:
    app: agent10008
  type: NodePort
  ports:
    - protocol: TCP
      port: 32008
      name: listener
      targetPort: 32008
      nodePort: 32008