apiVersion: apps/v1
kind: Deployment
metadata: 
  name: epos
  labels: 
    app: epos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epos
  template:
    metadata:
      labels:
        app: epos
    spec:
      imagePullSecrets:
      - name: 
      containers:
      - name: epos
        image: zeinabne/smotec:servicdistributor
        imagePullPolicy: Always
        ports:
        - containerPort: 32500
        - containerPort: 32501
        args: ["32500", "32501"]
        volumeMounts:
        - name: testbedconfig
          mountPath: /tmp/conf/TestbedConfig.json
          subPath: TestbedConfig.json
      volumes:
      - name: testbedconfig
        configMap:
          name: testbedconfig
      nodeSelector:
        nn: master
---
apiVersion: v1
kind: Service
metadata:
  name: epospro
spec:
  selector:
    app: epos
  type: NodePort
  ports:
    - protocol: TCP
      port: 32500
      name: listen
      targetPort: 32500
      nodePort: 32500
---
apiVersion: v1
kind: Service
metadata:
  name: eposcon
spec:
  selector:
    app: epos
  type: NodePort
  ports:
    - protocol: TCP
      port: 32501
      name: response
      targetPort: 32501
      nodePort: 32501