apiVersion: apps/v1
kind: Deployment
metadata: 
  name: veh1
  labels: 
    app: veh1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veh1
  template:
    metadata:
      labels:
        app: veh1
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: veh1
        image: zeinabne/edge-testbed:vehagent
        imagePullPolicy: Always
        ports:
        - containerPort: 32302
        args: ["1", "zeinabne/edge-testbed:", "epos"]
      nodeName: master-virtualbox
---
apiVersion: v1
kind: Service
metadata:
  name: veh1-service
spec:
  selector:
    app: veh1
  ports:
    - protocol: TCP
      port: 32302
      name: listen
      targetPort: 32302
