apiVersion: apps/v1
kind: Deployment
metadata: 
  name: agent10006
  labels: 
    app: agent10006
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent10006
  template:
    metadata:
      labels:
        app: agent10006
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: agent10006
        image: zeinabne/edge-testbed:vehagent1
        imagePullPolicy: Always
        ports:
        - containerPort: 32006
        args: ["10006", "2000", "50", "230", "80", "1"]
      nodeSelector:
        nn: master
---
apiVersion: v1
kind: Service
metadata:
  name: agent10006-service
spec:
  selector:
    app: agent10006
  type: NodePort
  ports:
    - protocol: TCP
      port: 32006
      name: listener
      targetPort: 32006
      nodePort: 32006