apiVersion: apps/v1
kind: Deployment
metadata: 
  name: agent1
  labels: 
    app: agent1
spec:
  replicas: 1
  selctor:
    matchLabels:
      app: agent1
  template:
    metadata:
      labels:
        app: agent1
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: agent1
        image: zeinabne/edge-testbed:pub
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadate:
  name: agent1-service
spec:
  selector:
    app: agent1
  type: LoadBalancer
  ports:
    - protocol: TCP
    port: 8083
    targetPort: 8081
    nodePort: 30001