apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edge0
  labels: 
    app: edge0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge0
  template:
    metadata:
      labels:
        app: edge0
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: edge0
        image: zeinabne/edge-testbed:edges
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
        args: ["0"]
      nodeSelector:
        nn: master
---
apiVersion: v1
kind: Service
metadate:
  name: edge0-service
spec:
  selector:
    app: edge0
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
      nodePort: 30030