apiVersion: apps/v1
kind: Deployment
metadata: 
  name: agent10009
  labels: 
    app: agent10009
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent10009
  template:
    metadata:
      labels:
        app: agent10009
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: agent10009
        image: zeinabne/edge-testbed:vehagent1
        imagePullPolicy: Always
        ports:
        - containerPort: 32009
        args: ["10009", "2000", "170", "80", "80", "1"]
      nodeSelector:
        nn: master
---
apiVersion: v1
kind: Service
metadata:
  name: agent10009-service
spec:
  selector:
    app: agent10009
  type: NodePort
  ports:
    - protocol: TCP
      port: 32009
      name: listener
      targetPort: 32009
      nodePort: 32009