apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edge0
  labels: 
    app: edge0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge0
  template:
    metadata:
      labels:
        app: edge0
    spec:
      imagePullSecrets:
      - name: 
      containers:
      - name: edge0
        image: zeinabne/smotec:edgeagent
        imagePullPolicy: Always
        ports:
        - containerPort: 32300
        - containerPort: 32100
        - containerPort: 32200
        args: ["0"]
        volumeMounts:
        - name: testbedconfig
          mountPath: /tmp/src/conf/TestbedConfig.json
          subPath: TestbedConfig.json
      volumes:
      - name: testbedconfig
        configMap:
          name: testbedconfig
      nodeSelector:
        nn: worker1
---
apiVersion: v1
kind: Service
metadata:
  name: edge0-listen
spec:
  selector:
    app: edge0
  type: NodePort
  ports:
    - protocol: TCP
      port: 32300
      name: listen
      targetPort: 32300
      nodePort: 32300
---
apiVersion: v1
kind: Service
metadata:
  name: edge0-response
spec:
  selector:
    app: edge0
  type: NodePort
  ports:
    - protocol: TCP
      port: 32100
      name: response
      targetPort: 32100
      nodePort: 32100
---
apiVersion: v1
kind: Service
metadata:
  name: edge0-trafmon
spec:
  selector:
    app: edge0
  type: NodePort
  ports:
    - protocol: TCP
      port: 32200
      name: trafmon
      targetPort: 32200
      nodePort: 32200