apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edge1
  labels: 
    app: edge1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge1
  template:
    metadata:
      labels:
        app: edge1
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: edge1
        image: zeinabne/edge-testbed:edges
        imagePullPolicy: Always
        ports:
        - containerPort: 8101
        args: ["1"]
      nodeSelector:
        nn: master
---
apiVersion: v1
kind: Service
metadate:
  name: edge1-service
spec:
  selector:
    app: edge1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8101
      targetPort: 8101
      nodePort: 30031