apiVersion: apps/v1
kind: Deployment
metadata: 
  name: agent10005
  labels: 
    app: agent10005
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent10005
  template:
    metadata:
      labels:
        app: agent10005
    spec:
      imagePullSecrets:
      - name: 
      containers:
      - name: agent10005
        image: zeinabne/smotec:vehicleagent
        imagePullPolicy: Always
        ports:
        - containerPort: 32005
        args: ["10005", "100", "200", "80", "1"]
        volumeMounts:
        - name: testbedconfig
          mountPath: /tmp/src/conf/TestbedConfig.json
          subPath: TestbedConfig.json
      volumes:
      - name: testbedconfig
        configMap:
          name: testbedconfig
      nodeSelector:
        nn: master
---
apiVersion: v1
kind: Service
metadata:
  name: agent10005-service
spec:
  selector:
    app: agent10005
  type: NodePort
  ports:
    - protocol: TCP
      port: 32005
      name: listener
      targetPort: 32005
      nodePort: 32005